services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare_streamlit_app
    ports:
      - "8501:8501" # Map container port 8501 to host port 8501
    volumes:
      - .:/app # Mount the current directory for development
    environment:
      - SRAG_SOURCE_URL=${SRAG_SOURCE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERP_API_KEY=${SERP_API_KEY}
      - TABLE_NAME=${TABLE_NAME}
      - LANGFUSE_BASE_URL=${LANGFUSE_BASE_URL}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: healthcare_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthcare_reports
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
